updating some spawn times on Vlad
jkachhad/Stormhalter pull request #1618
Opened 2022-04-22 02:48 UTC by TimPickup

Nothing Major. Bug fix for possible vlad not spawn + reasonable spawn time for vlad tower. Currently in HC each layer respawns in 5 mins!

Tower 1: Was 15-20 mins Now 2h30-3h
Tower 2: Was 15-20 mins Now 2h30-3h. Also changed Max spawns to 6 just because there are only 6 that are setup so 8 is impossible.
Tower 3: Was 15-20 mins Now 2h30-3h
Vlad: Was 3h-5h Now 3h-4h. Also changed max to 5 as otherwise there is a 1 in 4 chance Vlad would not spawn at all! 5 entities can spawn.

2022-04-22 12:29 UTC, sproatba commented
I'm totally against these time changes, part of the fight with vlad is getting up the tower and dealing with the tower if you have to jump or dealing with the top level if it respawns making the stairs unsafe.   if they need tuned fine, but the tower shouldn't be clear for the entire fight, unless you kill him quickly.  I'm also not sure why all these spawns are set for hours,  we don't have tons of facets, and they historically were much shorter.  Probably need a discussion on lair times, but 1hour spawns are a long time when you are sharing a facet, or organizing a group to farm a lair

2022-04-22 12:53 UTC, sproatba requested changes
At most tower should be bumped a few minutes, it should be back before vlad is dead unless you have a group nuking him quickly.

2022-04-22 12:56 UTC, Chilly021 commented
I think we are just experiencing the "Opal" speed issue right now. I don't know about changing time right now. Yes I died, and yes I knew the risk about jumping off the top and running back up. I'm not mad about it. I just was not thinking.

2022-04-22 14:28 UTC, SewerCzar commented
> I'm totally against these time changes, part of the fight with vlad is getting up the tower and dealing with the tower if you have to jump or dealing with the top level if it respawns making the stairs unsafe. if they need tuned fine, but the tower shouldn't be clear for the entire fight, unless you kill him quickly. I'm also not sure why all these spawns are set for hours, we don't have tons of facets, and they historically were much shorter. Probably need a discussion on lair times, but 1hour spawns are a long time when you are sharing a facet, or organizing a group to farm a lair

I agree with everything Angry said, including lair timers needing a bigger discussion.

The tower being murderous is the big part of the danger of the Vlad fight. If you can't kill him fast enough that the penultimate level has mobs back you might have to jump down and re-do the tower over again which is dangerous.

I think it's just part of the encounter and I personally like the concept of it.

2022-04-22 18:50 UTC, TimPickup commented
I have suggested shorter respawn times..
tower levels now 50-60 mins each .. so 16m to 20mins on HC

would that be a better reasonable respawn time ?

2022-04-23 12:45 UTC, Chilly021 commented
Be good time come up with a better time. I think 10 minutes is better than 5 on opal though.

2022-04-23 19:19 UTC, sproatba commented
I'm thinking leave it as is right now, he just got a new toy that people want so he'll be seeing some traffic.  We can get some feedback to make a better decision with.

2022-04-24 12:45 UTC, TimPickup commented
ok. May as well at lease put through the fixes though for how many spawn. 

Vlad could not spawn otherwise.

vladTower2 had a max of 8 but only max 6 creatures defined so may as well also set that to 6

2022-04-24 13:25 UTC, sproatba approved these changes

2022-04-24 13:30 UTC, sproatba commented
I went and solod vlad on 18/13 knight in SC.  He honestly wasn't that bad.  Tower respawn played a role in the fight, but with the regen rate on lairs where it is that seemed fine.  If the instant cast bug gets worked out he'll be a little more difficult I think.  Overall we need to decide where he fits in the progression of the BG and tune for that.  Right now he's one of the end game lairs to be done as you are finishing the bg, but his items are a little lacking for that.

2022-04-24 13:46 UTC, Chilly021 approved these changes

2022-04-24 18:16 UTC, SewerCzar approved these changes

2022-04-24 18:16 UTC, merged