Bloodlands - Swiftshield
jkachhad/Stormhalter pull request #1757
Opened 2022-09-20 19:01 UTC by Chilly021

Bloodlands - Swiftshield for Prototype

2022-09-20 20:39 UTC, zrikzlok submitted a review, later dismissed

2022-09-24 11:21 UTC, Chilly021 commented
@zrikzlok  this should be good again. Was waiting on the Art compile for Tenser. Above is the shield chosen.

2022-10-04 14:51 UTC, zrikzlok approved these changes

2022-10-17 13:50 UTC, sproatba submitted a review, later dismissed

2022-10-19 11:55 UTC, zrikzlok requested changes
Need to adjust for conflicts

2022-10-20 12:28 UTC, Chilly021 commented
I'll wait until @Tenscore's new Enu.xml goes in so there are no more conflicts.

2022-12-06 17:02 UTC, sproatba submitted a review, later dismissed

2022-12-08 23:53 UTC, Leolus approved these changes

2022-12-09 01:24 UTC, zrikzlok approved these changes

2022-12-09 19:14 UTC, Leolus approved these changes

2022-12-09 19:16 UTC, merged