Update Axe Glacier.mapproj
jkachhad/Stormhalter pull request #1891
Opened 2023-03-10 11:30 UTC by Tenscore

Minor tweaks to settle issues around East Ogre Caves. (Olorin approved.)

2023-03-10 14:16 UTC, Chilly021 approved these changes

2023-03-10 14:17 UTC, Chilly021 requested changes
Actually might need to change 48531 - and 3906 - you have the same direction twice there. (duplicates of the line before)

2023-03-10 14:19 UTC, Chilly021 reviewed
Corrected: Actually might need to change 48531 - and 3906 - you have the same direction twice there. (duplicates of the line before)

Just delete those lines.

2023-03-10 15:16 UTC, Chilly021 approved these changes

2023-03-10 16:08 UTC, Leolus approved these changes

2023-03-11 14:07 UTC, zrikzlok approved these changes

2023-03-11 14:07 UTC, merged